### ISSUE TITLE
Request /goto <player> system

### ISSUE THREAD

**Issue by beldah** [CubBossa/PathFinder#38]
Hello, i would like to request a feature about ask player to goto an other player with a request system. 
The steps can be like this :
1. the requester type /goto <player>
2. <player> receive the request and and click on accept or deny
3a. if accepted = a basic findlocation is write to the actual position of player (without update of position)
3b. if refused = deny the request and block him for 30 seconds

Optionnal good feature : add a system the block the /goto for everyone or only some speficied players

Thanks for your help and your great plugin CubBossa !

**Comment by CubBossa** [comment]
Okay so syntax might be `/findplayer`, the issue could also include `/findentity @e[...]`, which of course needs to be finetuned concerning permissions because it includes `/findplayer`.

Also, there should be a config way to set the refresh cycle of paths, so if admins want the paths to recalculate like every second for example, this should work for all `/find` variants

**Comment by CubBossa** [comment]
Accidentally closed
